# hello-kubernetes.yaml
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        env:
        - name: WWW_URL
          value: "https://github.com/myuser/website"
        image: myuser/www:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
